# Proxy server configuration
listen_addr: ":6380"

# Redis Cluster configuration
cluster_nodes:
  - "redis-node1:6379"
  - "redis-node2:6379"
  - "redis-node3:6379"

# Authentication settings
auth_enabled: true
tenant_map:
  tenant1: "tenant1:"
  tenant2: "tenant2:"
  tenant3: "tenant3:"

# Performance settings
max_connections: 1000

# Logging settings
log_level: "info"
